version: "3.9"
services:
  devopsdb:
    image: morukurthidurga/manual:db
    ports:
      - "3306:3006"
  application:
    image: morukurthidurga/manual:app
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
