version: "3.9"
services:
  devopsdb:
    image: morukurthidurga/automation:db
    ports:
      - "3306:3306"
  application:
    image: morukurthidurga/automation:app
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
